### ISSUE TITLE
Character creation age modifier is broken

### ISSUE THREAD

**Issue by InsertWarthog** [cmss13-devs/cmss13#5636] opened 2024-02-02 09:23 UTC
### Testmerges

#5007, #5392 if you want pull requests being TM'd.

### Round ID

20695

### Description of the bug

Tried modifying age on my haracter, it didn't let me change the number, it only went 19 then to 90.

### What's the difference with what should have happened?

It should've allowed you to y'know, change the age to whatever number you input within 19 and 90.

### How do we reproduce this bug?

1. Open character creation
2. Open age bar
3. Try and type some number for a characters age.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by harryob** [comment] 2024-02-02 09:39
duplicate of #5610 (but i should've given that one a more obvious title!)

**Comment by harryob** [comment] 2024-02-02 09:41
Duplicate of #5610

**Closed by harryob** 2024-02-02 09:41 UTC
Labels: Bug
