### ISSUE TITLE
USCM tactical map upload error

### ISSUE THREAD

**Issue by BAKACIRNONINE** [cmss13-devs/cmss13#6335] opened 2024-05-26 09:43 UTC
### Testmerges

#5957: 'OT CAS rocket' by iloveloopers at commit 624c3a8523 #6163: 'Heavy Sniper Part 2 - The Heavying' by Kaga-404 at commit 438587131c #6188: 'Research xenomorph "dissections"' by kiVts at commit 19058277f8 #6225: 'Research major property rebalance' by iloveloopers at commit 2294031ec3 #6039: 'Project ARES TM Holder (v5)' by realforest2001 at commit ec3359080d

### Round ID

22365

### Description of the bug

While I draw with 2 different colors with multiple lines, tmap can't upload
But while I only draw a circle or within 2 lines with a single color, it works fine

### What's the difference with what should have happened?

Tamp should upload with different colors and multiple lines

### How do we reproduce this bug?

1. use the concel at cic
2. draw lines with different colors
3. Hit upload button, can't announce or upload
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment] 2024-05-28 03:55
I can confirm that some reason now the map is extremely restrictive on the svg complexity, but I am not sure why at the moment.

**Comment by Drulikar** [comment] 2024-05-28 20:47
Issue appears to be a byond issue. Works as intended on 515.1627

**Comment by vero5123** [comment] 2024-05-31 22:49
fuqqqqqq

**Comment by Drulikar** [comment] 2024-06-05 02:16
Resolved in 515.1640

**Closed by Drulikar** 2024-06-05 02:16 UTC
Labels: Bug, BYOND issue, Confirmed Bug
