### ISSUE TITLE
Unburying larva can spawn at dangerous locations when there is no hive core

### ISSUE THREAD

**Issue by Vicacrov** [cmss13-devs/cmss13#5818] opened 2024-02-26 13:58 UTC
### Testmerges

not relevant

### Round ID

21049

### Description of the bug

Roundstart, no queen, no hivecore. I joined with the "Join as Xeno" button, selected "buried larva". I spawned in a window, on southeast LZ1.

I should neither spawn in a window, nor in areas that are not deemed safe for larvae.

### What's the difference with what should have happened?

I think hives without a hive core should spawn buried larva in areas that the queen can select as a starting location.

### How do we reproduce this bug?

1. Start the game
2. Add larvae
3. Join as buried larva
4. Observe your too random location

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Vicacrov** [comment] 2024-03-05 08:53
Checked the code, apparently, unburrowing larvae spawn right next to living xenos if there is 1) no queen 2) no hivecore.

I ended up spawning next to a xeno who was engaging survivors, so this is not a bug, it is just (imo) terrible design. Spawning in a window tile is a bug, though.

**Comment by ItsVyzo** [comment] 2024-08-27 19:33
Closing - Not a bug (quite literally) just how code works.

**Closed by ItsVyzo** 2024-08-27 19:33 UTC
Labels: Not a Bug
