### ISSUE TITLE
Window Frame Sprites Becoming Invisible

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#2531] opened 2023-01-30 21:55 UTC
### Testmerges

N/A due to length of time this issue has manifested however the images further down in this report had #2309 tested in it.

### Description of the bug

Sometimes when taking damage(noticed when explosive damage in particular was involved but also possibly from gunfire) that causes the window associated with the window frame to break, the window frame sprite becomes invisible. This leads to many frustrated players trying to move into the visibly unoccupied tile only to be stopped in their tracks.

### What's the difference with what should have happened?

Objects taking damage should not magically become invisible. Especially when those objects prevent movement. Attached is an image of a tile I found with the window frame made invisible and its corresponding window destroyed as well as the alt + click tile contents to prove that there is indeed a window frame since it is invisible.
![Invisible Window Frame](https://user-images.githubusercontent.com/105765670/215603302-58bfff3d-fff0-485f-a663-3c6b75fb9502.png)

Tile Contents: 
![Invisible Window Frame Tile Contents](https://user-images.githubusercontent.com/105765670/215603330-1f5c4ddd-5dd8-4466-b1b5-9fb1f5af93ea.png)

### How do we reproduce this bug?

Unfortunately, I am unable to replicate the issue on demand however it happens VERY often on Chance's Claim as well as Kutjevo Refinery for whatever reason. Over the months I have observed a window frame becoming invisible a few times and every time it involved some sort of explosive damage like a mortar or grenade. No issue report existed about window frames so I thought I would finally bring attention to it.

### Issue Bingo

- [x] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by NewyearnewmeUwu** [comment] 2023-02-20 01:16
I replicated this today on Solaris Ridge, in ETA.

**Comment by Superwelder** [comment] 2023-02-21 07:00
> I replicated this today on Solaris Ridge, in ETA.

I will update the report! Thanks for bumping the post!

**Comment by usnpeepoo** [comment] 2023-04-27 14:51
This has been a longstanding bug with windows, i've seen it since 2021. I believe it is caused by explosion damage which would normally destroy the window instead breaking the glass but leaving an invisible bodyblocking frame.

**Comment by Huffie56** [comment] 2023-08-03 09:52
i think this is outdated and the instance where it as been mention as been fixed. marking it with cleanup flagged will be close this week if no update..
could have been fix by:
https://github.com/cmss13-devs/cmss13/pull/3613
and some other PR that don't mention it....

**Comment by Huffie56** [comment] 2023-08-08 11:58
still something that happen apparently shiva maybe...

**Comment by ihatethisengine** [comment] 2023-08-25 08:53
Couldn't reproduce it at all. I know it's a real issue, but need proper steps to reproduce. Explosions doesn't seem to be the reason, at least I couldn't get the bug using explosions.

**Closed** 2023-10-02 14:17 UTC
Labels: Bug
