### ISSUE TITLE
Xenos getting hit with automatic fire mode doesn't display correctly

### ISSUE THREAD

**Issue by ondrej008** [cmss13-devs/cmss13#4499] opened 2023-09-24 23:40 UTC
### Testmerges

#4391, #4463, #4427

### Description of the bug

I'm not certain if this is the case but it seems that weapons on the automatic firemode don't display all the get hit messages.
Like if you hold down LMB on a xeno and it fires 10 bullets it only shows 1 message.

I haven't tested this but as a xeno I am 100% getting less hit messages than how many times I am getting hit.
This is especially noticeable with SGs.

### What's the difference with what should have happened?

One hit should mean one message.

### How do we reproduce this bug?

1. Marine with weapon set to full auto
2. Xeno
3. Shoot xeno with full auto while testing how many bullets hit versus. how long the button is held

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Zonespace27** [comment] 2023-09-25 00:06
Dupe of #4348

**Closed by Zonespace27** 2023-09-25 00:06 UTC
Labels: Bug

**Comment by ondrej008** [comment] 2023-09-25 00:33
my bad
