### ISSUE TITLE
Inconsistancies with the Shotgun Sentry.

### ISSUE THREAD

**Issue by NNJTM** [cmss13-devs/cmss13#1764] opened 2022-11-29 16:23 UTC
## Testmerges:
-[#1546](https://github.com/cmss13-devs/cmss13/pull/1546)
-[#1562](https://github.com/cmss13-devs/cmss13/pull/1562)
-[#750](https://github.com/cmss13-devs/cmss13/pull/750)
-[#1760](https://github.com/cmss13-devs/cmss13/pull/1760)
-[#1224](https://github.com/cmss13-devs/cmss13/pull/1224)

## Description
Watching the Shotgun Sentry from a ghosted position revealed to me that pellet count is Inconsistent from what it should be.  

## Difference between expected and actual behavior
The Shotgun Sentry should shoot regular old Buckshot. 4 pellets, 65 damage each pellet. It seems inconsistent, hitting for less pellets even at point blank range.

## Steps to reproduce
1.) Place shotgun sentry. 
2.) Place enemy in range.
3.) Check logs and witness the inconsistent pellet count.

## Issue bingo (not required to be all checked)

- [x ] Issue could be reproduced at least once
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment] 2022-11-29 17:18
Tested this on live server when it was reported. Sentry on thunderdome was shooting all the additional pellets as intended, but logs show sentries in the field proper only ever hitting with the main shell. Needs investigation.

**Comment by NNJTM** [comment] 2022-11-29 17:54
> Tested this on live server when it was reported. Sentry on thunderdome was shooting all the additional pellets as intended, but logs show sentries in the field proper only ever hitting with the main shell. Needs investigation.

To Clarify, this was on the map LV-642. In case that matters.

**Comment by usnpeepoo** [comment] 2022-12-02 04:51
On a different note, shotgun sentries are kind of wacky. On a very laggy, high-pop round of LV I was playing runner and triggered the shotgun sentry but did not get immediately shot by it. Almost a minute later, I was carrying a capture and suddenly was hit by the triggered shotgun sentries pellets far away from it and went into crit instantly. I don't know if its a code related issue or a server side issue, but just wanted to say.

**Comment by Ansekishokuu** [comment] 2024-10-30 10:49
Fixed with #7406

**Closed** 2024-10-30 16:39 UTC
Labels: Bug, Confirmed Bug
