### ISSUE TITLE
new smartfridge UI broke the turing

### ISSUE THREAD

**Issue by Weuyn** [cmss13-devs/cmss13#1931] opened 2022-12-12 22:47 UTC
### Testmerges

nope

### Description of the bug

the turing can't grab chemicals from the smartfridge anymore

### What's the difference with what should have happened?

it should be able to grab chemicals and delete empty bottles

### How do we reproduce this bug?

1. put vial of souto in vialbox into the turing
2. put souto cans into smartfridge
3. try to run turing
4. error, souto not found

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ItsVyzo** [comment] 2023-04-29 16:21
Can't reproduce, was this fixed?

**Comment by Huffie56** [comment] 2023-05-11 13:32
concerned PR that added the TGUI for it.
https://github.com/cmss13-devs/cmss13/pull/1623

**Comment by Huffie56** [comment] 2023-05-12 13:47
i fallowed the step everything work as intended.
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/bcae9594-c279-421a-8f8d-19758d7c8f0c)
i think you can delete this issue @ItsVyzo

**Comment by Huffie56** [comment] 2023-05-12 19:14
hello @usnpeepoo  i have tested this as you can see above can't reproduce it so i assume it's been fixed.

**Comment by usnpeepoo** [comment] 2023-05-12 21:36
Closing

**Closed by usnpeepoo** 2023-05-12 21:36 UTC
Labels: Needs Reproducing
