### ISSUE TITLE
Some bullets can sometimes insta kill (maybe just IFF ones)

### ISSUE THREAD

**Issue by CrazySquirrel7O** [cmss13-devs/cmss13#4765] opened 2023-10-22 02:29 UTC
### Testmerges

#4475, #4627, #4623, #4699, #4723, #4696, #4558 

### Round ID

19177

### Description of the bug

Playing as xeno, had more than 70% health (at least) and got hit by one single smart gunner bullet, died and got gibbed instantly, ahelped it and biolock after some log searching told me that indeed I had only been hit once and to bug report it.

Here is a screenshot of the transition from alive do dead, at the top you can see I was alive (was going to use acid spray), then I could see dead chat.
https://gyazo.com/30fd896ecf4d302e28c815cfbbda3f43

### What's the difference with what should have happened?

I should have just taken about 20-25 damage maximum and kept on, instead I died.

### How do we reproduce this bug?

1.Play xeno
2.Get hit by some bullet (If biolock is right probably needs to be IFF)
3.Pray the bug repeats
4.If you die even if you had a lot of health it worked
5.Else repeat

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by CrazySquirrel7O** [comment] 2023-10-22 02:35
I don't use Github very much so if you need to ask me something just @ me on the CM discord as Squirrel/ Ava B/ AV-B

**Comment by ihatethisengine** [comment] 2023-10-22 09:50
What caste and strain were you playing?

**Comment by Biolock1** [comment] 2023-10-22 10:52
They were playing a praetorian. I just had another player ahelp about the same incident happening with them. They were shot by an M4RA one time, and the M4RA had a smartscope.

**Comment by ihatethisengine** [comment] 2023-10-22 11:33
Well, this is really weird. I couldn't reproduce it no matter what I tried and I didn't find anything in my code that could affect damage. And not like other TMed PRs could cause the issue either. The fact the bug is reoccurring is very concerning. I'll be looking into it but please tell me if it happens again. Kinda weird it didn't happen yesterday or the day before, but maybe people just assumed nothing wrong happened.

**Comment by CrazySquirrel7O** [comment] 2023-10-22 11:56
It was a praetorian with the warden strain.

**Comment by ihatethisengine** [comment] 2023-10-22 12:08
https://github.com/cmss13-devs/cmss13/pull/4645
Might be the reason theoretically? It does mess with bullet traits and time seems to match and there were other weird occurrences today that didn't involve IFF. 

> I recently observed an incident of a larva tanking 30 bullets from a m41a without dying, I'd be concerned if this is occuring to other regular xenos
it was in ETA, a larva ran out of the hive to the front and got shot, it fell into crit but it was shot a subsequent 30 times before it healed and escaped
it was earlier today

**Comment by Biolock1** [comment] 2023-10-22 12:23
It's happening frequently enough that we should be able to narrow down whether it's this IFF PR by simply isolating it, no?

**Comment by ihatethisengine** [comment] 2023-10-22 12:39
Well if it happened only twice and both instances were today and there is no clear way to reproduce the bug, then not really. I do suspect https://github.com/cmss13-devs/cmss13/pull/4645 because it touches bullet traits (such as IFF) in a way it's not easy to see the consequences, while the IFF PR doesn't really touch anything related to bullets (except pure damage, but that's a simple number change). I'll do more tests to try to find the issue.

**Comment by ihatethisengine** [comment] 2023-10-22 12:46
Although fira says it wasn't live when the issue was created, so probably not.

**Comment by Lagomorphica** [comment] 2023-10-22 16:32
happened to me just last round (19186) on LV-624

crusher full HP + shield got hit by a M4RA round instantly dead + gibbed
also killed the queen

**Comment by Biolock1** [comment] 2023-10-23 02:01
Ah yes, that's the other commonality between them. It always seems to gib the body.

**Comment by Wintermote** [comment] 2023-10-23 02:46
During the first round of the IFF PR, I accidentally PB'd a marine with an M4RA and he instantly died. I don't know how much health he had but the medic treating him said he had 200-something damage. I thought it was really weird because it was just one hit and BOOM straight up completely dead instantly. Not even the normal bit of lag time where you run around for 30 seconds in crit but the game doesn't recognize it yet. He was just instantly dead.

Because I didn't know his health before I just assumed he'd already taken damage but since this report is here I'll add the anecdote that there might be something to it.

**Comment by ihatethisengine** [comment] 2023-10-23 13:56
Both bugs should be fixed in the PR. If the PR gets rejected I might port PB fix in a different PR.

**Comment by Huffie56** [comment] 2023-12-09 17:35
hello is this fixed @ihatethisengine ?

**Comment by Huffie56** [comment] 2023-12-10 08:20
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/cead2cad-049c-4076-a1b4-2eb5f962fa81)

**Closed by Huffie56** 2023-12-10 08:20 UTC
Labels: Bug
