### ISSUE TITLE
Reactions via Condiment Application

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#363] opened 2022-05-23 06:46 UTC
## Description

You can create reactions by applying a condiment to a food item.

## Difference between expected and actual behavior

It seems a bit odd for a solid food item to act like a container or solution that chemicals can be dumped into and reacted.

## Steps to reproduce

1. Acquire CHUNK box.
2. Unwrap CHUNK box.
3. Acquire empty condiment container (you can even drain out one of the hot sauce bottles).
4. Fill condiment container with water.
5. Apply water condiment to CHUNK box repeatedly.
6. Hear the bubbling, and receive messages about the solution bubbling.
7. Insert CHUNK box into soda fountain.
8. Open soda fountain.
9. Observe that the "glass contents" now includes a lot of hot chocolate (coco powder + water = hot chocolate).
10. Enjoy liquid CHUNK?

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment] 2022-11-27 12:18
Was able to reproduce this it's funny but.
every food item are coded as reagent container... that's the way it work it's not a bug i think.

**Comment by Huffie56** [comment] 2023-05-07 17:53
@harryob i think this is intended to work like that and it's not an issue... what do you think ? can we close it?
after all all food item work like that...

**Comment by Huffie56** [comment] 2023-05-19 07:51
hello @ItsVyzo and @usnpeepoo i think this isn't an issue i ask for a confirmation and i got this from segrain.
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/b74373c1-323b-4ad9-8174-03ac4f10a3d1)
so now it's for you to see if it's enough to close the issue...

**Comment by Huffie56** [comment] 2023-08-01 12:19
there is no issue there it is working as intented.

**Closed by Huffie56** 2023-08-01 12:19 UTC
Labels: Oversight, Consistency Issue

**Comment by Weuyn** [comment] 2023-08-01 12:25
if you do the same thing with milk you get chocolate bar candy items spawned under you

**Comment by Huffie56** [comment] 2023-08-01 16:45
> 

that's the recipe to do them it's normal
