### ISSUE TITLE
Depricated Node.js version makes Windows 11 machines refuse to compile and run a test environment

### ISSUE THREAD

**Issue by silencer-pl** [cmss13-devs/cmss13#4782] opened 2023-10-25 14:39 UTC
### Testmerges

Not relevant

### Round ID

Not relevant

### Description of the bug

dependencies.sh currently lists NODE_VERSION=14 and NODE_VERSION_PRECISE=14.16.1 which installs Node.js of that exact number, which is four major release numbers behind the current implementation. 

As Microsoft considers that version depreciated, Windows 11 will no longer run it at all, deeming it "incompatible". This prevents running test environments on current Windows machines. 

A "quick and dirty" fix to this is getting the current LTS version from the Node.js webpage and putting the updated node.exe into the tools\bootstrap.cache\node-v14.16.1-x64 of your local CM repo.

I'd put up a fix MR myself, but I discovered this too late into changes to my own fork and can't really be bothered to make a separate branch pointing back to the CM repo to do a proper merge request. I suggest the current LTE one, 20.9.0 which most likely would require you to change NODE_VERSION=20 (which by the way I don't think is used at all and seems redundant since you guys declare PRECISE and only call for it in the batch file) and NODE_VERSION_PRECISE = 20.9.0

NOTE: I THINK this is the only place where the version is called, but I may be wrong as I didn't want to waste too much time on it. I didnt find any other NODE_VERSION_PRECISE calls and that is what the node.bat file seems to call for when downloading Node.js

### What's the difference with what should have happened?

The infamous build.bat fails because Node.js refuses to run on Windows 11 systems.

I'd expect it to launch a test instance as usual, as it does when I put an updated Node.exe into the above folder.

### How do we reproduce this bug?

- Have an updated Windows 11 machine.
- Try to compile CM via build.bat without Node.js installed into the repo, as is its "natural" state.
- Despair, o ye unworthy as Microsoft says NO to depreciated software.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by fira** [comment] 2023-10-25 14:53
Did you test if building + CI just works with v20? With any luck we can just bump the pinned version in place

**Comment by fira** [comment] 2023-10-25 15:11
Seems NODE_VERSION_PRECISE is used by juke and TGS and NODE_VERSION only by CI
CI bootstraps manually with install_node.sh before calling juke build script which boostraps using PRECISE - i have no idea why

**Comment by silencer-pl** [comment] 2023-10-25 15:16
> Did you test if building + CI just works with v20? With any luck we can just bump the pinned version in place

Yes, it resolved all issues and loaded both the master and stable branches with no apparent faults. Node also has a "stable" and "newest" branch and 20.9.0 is the current "stable" version hence my suggestion. 

>Seems NODE_VERSION_PRECISE is used by juke and TGS and NODE_VERSION only by CI
CI bootstraps manually with install_node.sh before calling juke build script which boostraps using PRECISE - i have no idea why

Hence I edited in my note, I too was a bit confused by what is called by what and needs what from that file.

**Comment by harryob** [comment] 2023-10-26 09:32
the bootstrap runs fine for me on multiple windows 11 installations (my laptop and pc both run w11). this error looks far more like what would happen if your environment didn't incorporate https://github.com/cmss13-devs/cmss13/pull/2915 and you cancelled the install prompt too quickly, see below. changes to core tgui should be upstreamed, regardless

https://github.com/cmss13-devs/cmss13/assets/55142896/86a04f77-5694-45dd-be1f-3f40bcbdccd2

and this is it working fine on windows 11


https://github.com/cmss13-devs/cmss13/assets/55142896/33983cfa-e63d-47dd-b3eb-0d2ccdb112a7

as the download process that causes this was fixed in 2915, this is not a bug

**Closed by harryob** 2023-10-26 09:32 UTC
Labels: Bug
