### ISSUE TITLE
Plasma sentry refuses to turn on and cannot be removed

### ISSUE THREAD

**Issue by Cooliecan** [cmss13-devs/cmss13#1446] opened 2022-11-06 00:35 UTC
I tried removing plasma sentry with a multitool that I had just bought and deployed, and my character started hacking it instead of packing it up and even when finishing hacking I still could not pack up the sentry with the multitool.

![image](https://user-images.githubusercontent.com/13284499/200148579-ca9fa027-dffd-4d8b-bc07-1f1081c514a7.png)

**Comment by Segrain** [comment] 2022-11-06 09:36
Duplicate of #1444.

**Closed by Segrain** 2022-11-06 09:36 UTC
