### ISSUE TITLE
Miniscule damage and minor pain overlay seem to last indefinitely unless you ingest something

### ISSUE THREAD

**Issue by ThePiachu** [cmss13-devs/cmss13#1536] opened 2022-11-13 10:52 UTC
## Description

On a few rounds I noticed minor pain effect lasts indefinitely if you were gently hit by something and don't take any meds. As soon as you take any chemical (even eating a fruit) you heal back up to 100%.

In my latest CT round I tested it: This is the scan after I got hit:

![image](https://user-images.githubusercontent.com/964559/201909746-32b51106-fbb2-495f-97b5-4a653ebb0b6f.png)

And the overlay didn't go away for 5 solid minutes until I ate a lime.

Got a similar persistent pain condition when I put an IV into my synth body and moved away, yanking the needle. The Synth got a pain overlay!

So I'm guessing we only check for clearing those effects when we apply meds or something, not during natural healing or a general life() process.

## Difference between expected and actual behavior

The various cosmetic effects of pain, drugs and so on should go away on their own after a while, but they don't.

## Steps to reproduce

1) Get gently hit by someone tossing something at you
2) Give a bit of time to heal
3) Scan health - you will be barely hurt
4) Wait - you will continue being barely hurt
5) Eat something - magically you're healed!

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment] 2022-11-13 22:02
You would need to ahelp next time so that he can check what's wrong. i know that since alcohol as been made safe you can't die and so you can drink ten can of beer and be drunk for a long time. same with drugs that can have high OD level and low degradation in you... the pain stuff is weird. dyloven reduce the effect of drugs and help with alcool to if i am correct.

**Comment by ThePiachu** [comment] 2022-11-15 11:32
I have done a little bit of testing and I think some confusion came from how long drunkenness takes to wear off (I think it used to be shorter?). Like if you take one beer you will be buzzed for the next half out it seems.

Tried the Warlock's Velvet and all that and the overlay does go away on its own, but it is also a bit slow.

I think there might be something else to the pain overlay after someone throws an object at you. I'm guessing there is some kind of rounding error there where you heal to less than 1% damage and then the remaining less than 1% doesn't go away for the longest time?

![image](https://user-images.githubusercontent.com/964559/201908904-90a4105b-3763-4f6c-9ada-fdeaa7d04786.png)

I had that overlay for 5 solid minutes AFTER I did the scan in the screenshot, and the overlay only went away after I ate a lime.

So I'm guessing some proc about healing doesn't get called enough because of some rounding error and we are left dangling with a small pain overlay.

**Comment by ThePiachu** [comment] 2022-11-15 11:36
Updated the issue to reflect the findings

**Comment by fira** [comment] 2022-11-17 22:38
That's be pretty weird considering the absolutely insane amount of things that are chugged down Life() ticker proc... are you sure it's not rather the pain system itself?
But yeah i've seen this happen before ingame too and it confused me. I assumed it was lingering pain for some good reason. But thinking back....

**Comment by Huffie56** [comment] 2023-08-05 09:13
tried to reproduce this it's probably been fixed in a PR? nobody update it with an experience of it

**Closed by Huffie56** 2023-08-05 09:13 UTC
Labels: Bug, Cleanup Flagged, Needs Reproducing
