### ISSUE TITLE
TM issue: Hive cores can be turned into pylons // This destroys the hive core

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#3993] opened 2023-07-25 10:24 UTC
### Testmerges

Xeno endgame content part 1: pylons and larva #3985 (its specifically for this testmerge)

### Description of the bug

![image](https://github.com/cmss13-devs/cmss13/assets/44538569/402d2e87-2299-44d1-b6db-d7d33091da2a)
Tested this in round as forsaken. Not SURE if this is intentional, but it seems unintentional

If you place a hive core near a comms relay and all the conditions are met (1:30 round time) it destroys the hive core and replaces it with a pylon. You can't place another hive core quickly either, since it gives you the hive core destruction cooldown.

### What's the difference with what should have happened?

Hive core should not be turned into hive pylon (probably)

### How do we reproduce this bug?

1. Place hive core near comms tower past 1:30 minute mark
2. Hive core is destroyed and replaced with pylon.
3. Hive core is on cooldown
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment] 2023-08-02 18:32
that could be something intended by the hive unless they can't build core again after cooldown end....

**Comment by Drulikar** [comment] 2023-08-03 23:25
Should already be resolved with some of the commits in the endgame pr; otherwise we've not been able to reproduce the problem anymore.

**Closed by Drulikar** 2023-08-03 23:25 UTC
Labels: Bug
