### ISSUE TITLE
Vampire Rush not properly reducing CD if hit

### ISSUE THREAD

**Issue by Butlerblock** [cmss13-devs/cmss13#2836] opened 2023-03-14 02:34 UTC
### Testmerges

#2521, #2776, #2756, #2752, #2753, #2777

### Description of the bug

When properly hit, Vamp rush CD is never reduced. While I'm way too lazy to figure out the fix myself, I assume that the object is not properly given when nothing is passed into the apply_cooldown_override function, when "owner" is required(though owner might be defaulted, not entirely sure). Additionally, it's not even properly set to the right number of 30, as per the original PR's statement of "Reduced to three seconds if landed", whereas the current code(should) set it to 4 seconds. 

### What's the difference with what should have happened?

Rush cooldown should be set to three seconds, but is defaulted to 6 seconds instead.

### How do we reproduce this bug?

1. Rush normally and miss a target and record time until off CD
2. Rush a target and land it and record time until off CD
3. Both are the exact same time.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment] 2023-08-03 09:45
fixed by https://github.com/cmss13-devs/cmss13/pull/3300 ?

**Comment by Huffie56** [comment] 2023-08-03 09:47
fixed by https://github.com/cmss13-devs/cmss13/pull/3300 ?
apparently wiki was wrong and their was unused code that make you think it would reduce CD if hit but it don't ...weird stuff...

**Closed by Huffie56** 2023-08-03 09:47 UTC
Labels: Bug, Needs Reproducing

**Comment by Butlerblock** [comment] 2023-08-04 04:05
![image](https://github.com/cmss13-devs/cmss13/assets/68832905/1ae30bcc-40f0-4d87-ae29-04b63974f499)
_Picture taken from Diego's original vampire strain PR_ https://github.com/cmss13-devs/cmss13/pull/955

This was not in fact unused code, this was an error made by either Diego's original vampire strain or Carlacs rework. This is still a bug. I did not notice the PR "Removing dead code", if I did I should have pointed this out, but this was intended by it's original owner, and as far as I am aware, was not intentionally removed by anybody.

**Comment by Drulikar** [comment] 2023-08-04 07:18
Most recent attempt to add it back that was closed: https://github.com/cmss13-devs/cmss13/pull/2938

Wiki was already updated to reflect this: https://cm-ss13.com/w/index.php?title=Lurker&diff=25517&oldid=24699

As it stands right now, it is working as intended.
