### ISSUE TITLE
items placed on tables/racks are invisible to the rightclicker

### ISSUE THREAD

**Issue by pedr69** [cmss13-devs/cmss13#1154] opened 2022-10-01 23:48 UTC
## Description
placed(not thrown) items get moved into the table, making them invisible to the rightclicker's eye, you need to stand next to it and alt click to see what's on the table
https://github.com/cmss13-devs/cmss13/blob/9b685964ab605dbc66ba2ac87d60d59d2054f0c6/code/game/objects/structures/surface.dm#L57
supposedly done to save on performance, but does it really?
i'd expect light updates and weedspread to be the main performance killers(and atmos but i dont think that's simmed), not stationary items
all the people i've seen throw stuff onto tables/racks, which doesn't forcemove and cancels out the supposed performance gain, no? unless it's the premapped tables/racks 

## Difference between expected and actual behavior

expected: right click table, see all the items
actual: right click and it's just the table

## Steps to reproduce

put item on table/rack
or find a premapped table/rack

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by pedr69** [comment] 2022-10-02 12:34
putting an item on a table, alt clicking, and then right clicking the item in the alt click menu will pick up the item while keeping a ghost copy of it on the table

**Comment by Superwelder** [comment] 2022-10-03 07:02
This was intentional when the patch that merged items into tables to cut down on total item counts on the server was added. They do not show up on right click BECAUSE they are part of the table. It is just the table sprite you are right clicking even if it looks like the object you want to click. This also causes xenos trying to melt objects merged with tables to melt the table instead. Forcing them to destroy the table to melt said object. Is it a perfect system, no. But if I remember correctly, the patch helped a LOT with lag on the server so it was acceptable.

**Comment by pedr69** [comment] 2022-10-03 14:42
are there really that many items on tables on the map? reducing the amount of marines vending out 40 magazines and attachments in the prep room floors seems like the more reasonable way to lower itemcount instead of "lol tables are silly now"
if it's the premapped tables and racks in maint, why not have pregenerated ones merged into the table, but player placed items actually exist on top to allow rightclicking? surely there aren't so many table users to grind the server to a halt

i do however still think the performance issue was caused by something else, on no other server does growing a thousand tomatoes lag (until they're put on a conveyor belt or welderbombed or similar)

**Comment by stanalbatross** [comment] 2022-10-07 10:34
not a bug

**Closed by stanalbatross** 2022-10-07 10:34 UTC
