### ISSUE TITLE
combi sticks runtime when thrown

### ISSUE THREAD

**Issue by deathrobotpunch** [cmss13-devs/cmss13#5356] opened 2023-12-31 22:32 UTC
### Testmerges

#5298: 'Polish Dropship Weapons UI' by Drulikar at commit ea03c591c4 #5246: 'Adds  antispam check similar to what sentrygun has to m56d' by cuberound at commit f53759f78e #5113: 'Modifies and Re-Enables Shivas Snowball' by Steelpoint at commit 0e3fb8ac0e #5285: 'X17 Riot Breaching Charge' by realforest2001 at commit 95655f2e1e #5153: 'Status Effects - Part 3A (v2) - Daze Refactor' by fira at commit e8796e1f05 #5294: 'Yautja Actions Update (/QOL changes)' by BeagleGaming1 at commit 06faa59553 #5086: 'Adds the XM51 Breaching Scattergun' by VileBeggar at commit a6c9afdfda #5337: 'Fixes playing cards' by fira at commit 3b08cf34e4 #5280: 'Changes to bone repairing' by BeagleGaming1 at commit 8db4f2c4c5 #5278: 'Xenos now see marines on the tacmap during hijack if xenos outnumber marines for more than 25%' by ihatethisengine at commit fa3d81032d #5122: 'Pylons now count only groundside marines, xenos get major boost to evo speed for 3 minutes after hijack' by ihatethisengine at commit e2f845cb7e

### Description of the bug

I was testing out yautja weapons and when I threw the combi stick my game crashed, I tested this multiple times.

### What's the difference with what should have happened?

not to runtime

### How do we reproduce this bug?

1. charge combi by killing a dude
2. throw
3. game crash
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment] 2024-01-01 07:49
This is likely caused by the TM: Yautja Actions Update (/QOL changes)

Please provide the error in the future. I assume it was this *warning* message? `Exception has occurred: item_pickup overridden. Use override = TRUE to suppress this warning` Or when you are yanking on no target? `Exception has occurred: Cannot read null.affected_atom`. Neither crash the game.

Runtimes 99% of the time do not result in a crash. You may simply just not be expecting VSC to halt execution when it encounters a runtime. Ever there's something too spammy when testing and you already know the runtime that is re-occuring you can toggle off automatic breakpointing of runtimes here: 
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/1b7da4d4-397b-4445-9846-d3e22ff7d7bf)

**Comment by deathrobotpunch** [comment] 2024-01-01 12:34
thanks alot, I just thought it was odd that whenever I threw it the server crashed

**Comment by Drulikar** [comment] 2024-01-17 15:50
Should be fixed as of https://github.com/cmss13-devs/cmss13/pull/5294

**Closed by Drulikar** 2024-01-17 15:50 UTC
Labels: Bug
