### ISSUE TITLE
Huggers not being hidden in resin hole.

### ISSUE THREAD

**Issue by Kiara-Miller** [cmss13-devs/cmss13#1216] opened 2022-10-09 14:06 UTC
## Description

Hugger staying visible and seemingly alive on a table, instead of hiding in a resin hole. Allegedly seen multiple times, but this is the first instance i am in a position to record.
Server Time: 2022-10-09 14:05:10
Round Time: 01:21
![image](https://user-images.githubusercontent.com/115281303/194761291-302df58f-b5f4-4bb7-baf1-c52d9ecabb6c.png)

## Difference between expected and actual behavior

They should not be visible on the table.

## Steps to reproduce

No clue at the moment.

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by usnpeepoo** [comment] 2022-10-31 00:39
I have attempted to reproduce this bug.
This isn't happening because of the hugger being thrown onto the table, rather it doesn't go into a trap if it is manually placed (clicked table) on a table.

**Comment by usnpeepoo** [comment] 2022-10-31 01:46
To clarify what i said above, this is because facehuggers "merged" into a table like any other item when they were put on a table. When this happened they just died on the table and never went into a resin hole/can't ever be picked up again unless the table was broken or flipped.

**Closed** 2022-11-01 15:24 UTC
Labels: Bug
