### ISSUE TITLE
PFC Engie Pamphlet =/= M56D/M2C's Engie Pamphlet 

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#265] opened 2022-05-10 04:46 UTC
## Description
If you buy a JTAC pamphlet and Engie pamphlet as a PFC, they only let you use one and on using the 2nd, it says as much, you can only use one.

However, by taking the M56D/M2C crate and its engie pamphlet, you can take JTAC and use the turret's pamphlet afaik to bypass this limit?

## Difference between expected and actual behavior
Using a the gun emplacement's engie pamphlet you can bypass the pamphlet limit

## Steps to reproduce
Using a the gun emplacement's engie pamphlet you can bypass the pamphlet limit

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by MidwayAtom** [comment] 2022-05-16 10:37
I would consider this as intended. Main traits and skills like JTAC or Engie are limited to the singular avoiding Meta Gaming. And in need of defence or weapon training that is quite narrow to these specific weapons that they are able to be used mostly in an emergency situation, these other pamphlets exist.

Will leave this open for now, to see if a dev or others have a voice on if this is a bug or intended.

**Comment by morrowwolf** [comment] 2022-05-17 08:07
It is explicitly laid out in the code that the machinegunner pamphlet bypasses the usual limit.  It also does not give you the full benefits of miniengi.

**Comment by nuklearcellphoneg** [comment] 2022-05-18 01:53
Oh, I see- talk about counter intuitive.

>0 construction skill
>1  engineering skill
>can't construct cades, but knows how to fix them

**Comment by MidwayAtom** [comment] 2022-10-30 10:18
As intended so closing.

**Closed by MidwayAtom** 2022-10-30 10:18 UTC
