### ISSUE TITLE
Xeno lamp

### ISSUE THREAD

**Issue by Artem-fp** [cmss13-devs/cmss13#2639] opened 2023-02-12 21:32 UTC
### Testmerges

#2203, #2613

### Description of the bug

1) Xeno devours a marine
2) Xeno start's making light

Maybe there more to this "lamp problem", but my problem occurred with this 2 simple steps.

### What's the difference with what should have happened?

No light from xeno i guess?

### How do we reproduce this bug?

1) Xeno devours a marine
2) Xeno start's making light

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by usnpeepoo** [comment] 2023-05-12 19:05
This is reproducible in a test server by devouring a marine with an active flashlight, player paneling yourself into the devoured marine and dropping the flashlight. This turns the xeno into an unending light source

**Comment by Drulikar** [comment] 2023-05-14 07:08
Reproduction steps don't seem to be specific enough to reproduce this issue for me. At most devouring doesn't trigger a light update for where they were devoured - but thats not stuck to the xeno - and dropping the flashlight actually fixes it (if dropping even should be allowed when devoured). Or is already fixed on the commit I am on (currently on https://github.com/cmss13-devs/cmss13/pull/3305/commits/ee308bdef922cbbcd8640f13f1dd92bac5e3856a ) What if anything are you doing different from https://youtu.be/___EPTQqHRA @usnpeepoo ?

**Comment by Huffie56** [comment] 2023-05-18 18:39
this issue on gitlab seem related.
https://gitlab.com/cmdevs/colonial-warfare/-/issues/751

**Comment by Huffie56** [comment] 2023-05-21 11:10
> Reproduction steps don't seem to be specific enough to reproduce this issue for me. At most devouring doesn't trigger a light update for where they were devoured - but thats not stuck to the xeno - and dropping the flashlight actually fixes it (if dropping even should be allowed when devoured). Or is already fixed on the commit I am on (currently on [ee308bd](https://github.com/cmss13-devs/cmss13/commit/ee308bdef922cbbcd8640f13f1dd92bac5e3856a) ) What if anything are you doing different from https://youtu.be/___EPTQqHRA @usnpeepoo ?

could just add a reset to caste_luminosity when a xeno regurgitate to be sure?
would gladly do it but i didn't found the place to put it....

**Comment by Drulikar** [comment] 2023-06-29 10:34
Is this still an issue after #3668 ?

**Comment by Huffie56** [comment] 2023-08-01 13:47
apparently still a thing.
![image](https://github.com/cmss13-devs/cmss13/assets/117036822/e127f8e6-a522-42ce-8ca8-72dd83e34b3f)

**Comment by Huffie56** [comment] 2023-08-01 13:50
apparently https://github.com/cmss13-devs/cmss13/pull/3669 didn't fixed all the occurrence....

**Comment by ItsVyzo** [comment] 2023-09-05 08:52
Maybe related/similar to #4339

**Comment by Huffie56** [comment] 2023-12-10 09:30
i think it's been fixed been a while since i saw a xeno emitting light...

**Comment by Huffie56** [comment] 2023-12-16 13:08
a week as pass nothing new time to close this issue...

**Closed by Huffie56** 2023-12-16 13:08 UTC
Labels: Bug, Cleanup Flagged, Needs Reproducing
