### ISSUE TITLE
bipod permanent undeploy sound

### ISSUE THREAD

**Issue by stanalbatross** [cmss13-devs/cmss13#949] opened 2022-08-26 21:30 UTC
## Description

bipod makes an undeploy sound every time you move even when it's not deployed when attached to a gun

only fixed by deleting the bipod

## Difference between expected and actual behavior

should not do this

## Steps to reproduce

nunk to fill it out

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Sernoh** [comment] 2022-08-26 21:31
I think I got either knocked by an explosion or warrior grabbed out of a bipod'd state with the HPR. Either way it spammed the bipod sound indefinitely loudly and obnoxiously

**Comment by Segrain** [comment] 2022-08-27 00:18
Duplicate of #700, most likely.

**Comment by Mister-moon1** [comment] 2022-08-27 01:16
Found out the cause, dropping the weapon with the bipod while the bipod is deployed will not undeploy the bipod instead trying to undeploy the bipod every time you move, causing slowdown and the noise to be made
this bug will not happen if there is a magharn on the gun and it goes to your suit slot, it will only happen if it drops to the floor
the sound however will only occur if someone else picks up the gun after the glitch is performed 
the glitch can be fixed by the person who the bug has occured to picking up the gun, and moving around

when it has no magharn, constant slowdown
https://streamable.com/1imly4

no bug with magharn (bug will occur if suit slot is filled)
https://streamable.com/nqk7yr

makes sound if someone else picks it up while bugged
https://streamable.com/fldlrm

**Comment by DoomLaser9** [comment] 2022-08-27 07:06
This is part of #559. When the other person picks up the "glitched" gun, they can run around with the bipod still deployed and granting them the buffs.

**Closed** 2022-12-28 20:04 UTC
Labels: Bug, Duplicate
