### ISSUE TITLE
Marines can resist out of grabs while stunned

### ISSUE THREAD

**Issue by NexusStorm1** [cmss13-devs/cmss13#5074] opened 2023-11-30 00:39 UTC
### Testmerges

#4986, #4866, #4997, #4939, #5054, #4842

### Round ID

19735

### Description of the bug

I couldn't nest a hugged marine since he kept resisting out of my grip. This also occurred before he was hugged; it was impossible to devour him until a hugger arrived to hug him (the hugger stun likely prevented him from resisting).

### What's the difference with what should have happened?

Stunned marines shouldn't be able to resist.

### How do we reproduce this bug?

1. Stun marine
2. Grab marine
3. Marine is able to resist out of the grab.
See attached clip
...

https://github.com/cmss13-devs/cmss13/assets/108187599/6fa1b4ae-f339-4c9e-b096-cf863ee733b0

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by fira** [comment] 2023-11-30 01:37
Technically the issue is wrong, Stunned marines can't resist, but that marine is knocked down, not stunned

That should be fixed next round onward by making both human and xeno tackle also stun

**Comment by NexusStorm1** [comment] 2023-11-30 02:07
Sentinel spit also needs this fix for hugged/unarmoured hosts (unless you've already fixed this).

**Comment by fira** [comment] 2023-11-30 02:16
Yeah i was going over it now, also Stun Batons, Paralysis slash, and such. Not making everything a stun, eg. shuttle flooring remains just flooring, but for most intent and purposes this doesn't matter -- mainly for snowflake interactions like resist, or if eg. you can take advantage of buckling to a chair to stay up and keep doing thnigs

**Comment by fira** [comment] 2023-11-30 02:17
There'll almost certainly be more issues in that style in the next few days testing

**Comment by zzzmike** [comment] 2023-11-30 05:12
Was gonna make a new report, but this is clearly related, so...

Tableslam doesn't work properly anymore (used disarm intent, aggressively grabbed someone, clicked on table, everything was as usual except they could resist immediately - previously you'd get the 'cannot resist in your current state' error for ~5 seconds or something.

**Comment by fira** [comment] 2023-11-30 10:50
Yeah readded a lot of missing stuns but some are still MIA, will look at tabling. Keep reporting em!

**Comment by fira** [comment] 2023-12-02 14:09
I'll close this as this should have been dealt with, open new issues or comment on PR if theres more

**Closed by fira** 2023-12-02 14:09 UTC
Labels: Bug
