### ISSUE TITLE
"perfect hijack" bug info

### ISSUE THREAD

**Issue by FGRSentinel** [cmss13-devs/cmss13#3] opened 2022-04-07 21:43 UTC
Copied from GitLab:
**Description**
As Fira and I identified a while back, the famous "1% chance to land on the pad" hijack thing isn't intentional and is actually fairly easy to replicate.

**Difference between expected and actual behavior**
As stated, the dropship should land in a random spot in the region the queen selects (unless AA interferes), but it's possible to bypass the hijack crash sequence through a quick trick.

**Steps to reproduce**

As queen, click the launch button on a locked dropship.
Acknowledge the launch as normal and select a crash target, but don't close out of the target select screen.
To maximize the chances of success, move the target select window so the confirmation is over the flight computer UI's launch button.
Wait for an indication of a tick processing, if possible to identify.
Click the target confirmation, then quickly quick launch on the flight control UI. Note that steps 3 and 4 are optional and only need to be done to guarantee that the bug is triggered successfully

**Specific information for locating**
This was actually something Fira mentioned to me and was first noted due to the below log irregularity:
ADMIN NICHE LOG: Queen (X) launched a shuttle using the 'Alamo' flight controls. x2
Fira noted that this log always came up in rounds where the dropship hijack would result in the ship landing on the pad, but didn't explain the trigger. As Fira explained to me, there's a quirk in shuttle code (I can't remember the specifics anymore, sadly) that causes launch requests for each ship to only process the most recent request once per tick. On top of that, when a launch request is made, it checks if the queen is the one making the launch request and if they've already completed the hijack launch steps before moving on to other options. From what I recall, the code checks a single variable that gets incremented after the queen finishes the normal hijack steps, which causes it to make any future requests from her to come back as "false" for eligibility to hijack. After having this explained, I tried a few things on a private repo and came up with the steps listed above. Functionally how the bug works is as follows:

The queen tries to launch normally, which the code correctly identifies as a hijack attempt and starts the two steps required to hijack.
The queen completes these steps and only then is the launch request set to be processed. The variable checked by the code is incremented to mark that the hijack has occurred. Depending on tick time, the request will process at some point within the next five seconds.
The queen attempts to launch again, but as the variable incremented, the hijack condition is now marked as "false" and the code moves through other possible conditions. As there's no block for if the request is made by the queen and the hijack is already in progress, it defaults to a standard launch request.
As only the most recent valid launch request is processed, the valid hijack launch is discarded and the second "standard" launch request is processed. The dropship will land in the hangar with flight time modifiers from fuel enhancers and flight optimizations applying. Of important note, the dropship will correctly block POs from launching the dropship and therefore prevents the Marines from triggering the bug.

**Length of time in which bug has been known to occur**
I've known the full details for how to trigger it and how it works for 2-3 months, but as far as I know this has been in since at least 2018-2019, long enough to be mistaken for an RNG feature. The most recent instance I've seen was about two months ago, but it may have been fixed since or just not have occurred during a round I was part of.

**Comment by Diegoflores31** [comment] 2022-04-21 23:51
so the issue is that the queen is able to press the launch button twice to make a perfect landing instead of a hijack ??

**Comment by FGRSentinel** [comment] 2022-04-27 17:36
> so the issue is that the queen is able to press the launch button twice to make a perfect landing instead of a hijack ??

Yeah. If memory serves it's a quirk with how it processes it that if she hits launch after confirming the crash target and before the tick processes, it wipes the "crash" bit of the hijack and lands the dropship in the hangar. Marines can't interact with it in any way except for things that alter the flight time (fuel enhancer or flight optimization) which reduces their prep time even more. The only positive for this on the Marine side is the bug is laughably easy to detect if you know how hijack and normal flights work, so if you know what to look for you can tell if it's going to crash somewhere or land in the hangar.

I'm not sure if using that knowledge would be acceptable though since it's related to the bug and how it works.

**Comment by mullenpaul** [comment] 2023-02-05 23:10
https://github.com/cmss13-devs/cmss13/pull/2446 should resolve this once it gets merged

**Comment by harryob** [comment] 2023-03-03 08:38
which it was

**Closed by harryob** 2023-03-03 08:38 UTC
Labels: Bug, Priority: High
