### ISSUE TITLE
Abovehead Chat Indicator sometimes doesn't go away (clientside?)

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#3217] opened 2023-05-03 05:38 UTC
### Testmerges

#3073: 'Squad Team Leader' by morrowwolf at commit 55a7eaf7ac #3088: 'Fixes offset issue for multithreading test' by LynxSolstice at commit 95d6c01a9c #2652: 'Say\Hearing performance 515 edition' by Git-Nivrak at commit 0c8a0b70a3 #3179: 'Dancer buff + Bug Fixes' by Git-Nivrak at commit 3985fd08a6 #3185: 'GAU buff. ' by Tisx1 at commit c75cbb5947 #3192: 'discord certification' by harryob at commit 46c90b2253

### Description of the bug

The Abovehead Chat Indicator (talky bubble thing) sometimes doesn't go away after your done talking. Reconnecting seems to fix this, which makes me think it might just be a clientside visual bug. It's still very annoying, either way though. 

### What's the difference with what should have happened?

A chat bubble should not become permanent after someone speaks.

### How do we reproduce this bug?

1. Have chat indicator on
2. Talk, get unlucky

I think turning off the preference for chat indicators while the bubble is still there also makes this bug happen
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment] 2023-05-06 23:53
Duplicate of #3215

**Comment by gitbirb** [comment] 2023-09-18 02:27
> Duplicate of #3215

Not a duplicate: although the bug is caused by the same preference.
I've figured out the cause though is that if you are speaking (the indicator is present) then disable your indicator, it stays permanent until you reconnect. It's probably a clientside visual bug, and MAY be caused by the buggy indicator in #3215

**Comment by ItsVyzo** [comment] 2024-08-31 01:16
Same general issue as #3215

**Closed by ItsVyzo** 2024-08-31 01:16 UTC
Labels: Bug, Duplicate, Confirmed Bug
